#pragma once

namespace beluga
{
    enum TLS_HANDSHAKE_TYPE
    {
	TLS_HELLO_REQUEST = 0x00,
	TLS_CLIENT_HELLO = 0x01,
	TLS_SERVER_HELLO = 0x02,
	TLS_CERTIFICATE = 0x0B,
	TLS_SERVER_KEY_EXCHANGE = 0x0C,
	TLS_CERTIFICATE_REQUEST = 0x0D,
	TLS_SERVER_HELLO_DONE = 0x0E,
	TLS_CERTIFICATE_VERIFY = 0x0F,
	TLS_CLIENT_KEY_EXCHANGE = 0x10,
	TLS_FINISHED = 0x14,
    };
}
